[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
samdwich = "4Fwq3dAeUA3dJcVoseiPAY8jNQmLgexADy6ciU1t6Bte"

[programs.mainnet]
samdwich = "4Fwq3dAeUA3dJcVoseiPAY8jNQmLgexADy6ciU1t6Bte"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
