[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
samdwich = "u4h8vBXwx3fqM8Yopqk8U7hBYJG75nyrWqBsy8cNUBE"

[programs.mainnet]
samdwich = "u4h8vBXwx3fqM8Yopqk8U7hBYJG75nyrWqBsy8cNUBE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
